#
# Copyright (C) 2011 NEC Corporation
#

TREMA = ../../../../trema

CC = gcc
AR = ar
RANLIB = ranlib

CFLAGS = $(shell $(TREMA)/trema-config --cflags) -std=gnu99 -D_GNU_SOURCE -g -fno-strict-aliasing -Werror -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Wfloat-equal -Wpointer-arith -I. -I..
LDFLAGS = $(shell $(TREMA)/trema-config --libs) -L../../../objects/lib -ltrema 

#SRCS_COMMON = utils.c
#OBJS_COMMON = $(SRCS_COMMON:.c=.o)

TARGET_EXAMPLE1 = example1
SRCS_EXAMPLE1 = example1.c
OBJS_EXAMPLE1 = $(SRCS_EXAMPLE1:.c=.o)

TARGETS = $(TARGET_EXAMPLE1) 
SRCS = $(SRCS_COMMON) $(SRCS_EXAMPLE1) 
OBJS = $(OBJS_COMMON) $(OBJS_EXAMPLE1)

DEPENDS = .depends

.PHONY: all clean

.SUFFIXES: .c .o

all: depend $(TARGETS)

$(TARGET_EXAMPLE1): $(OBJS_EXAMPLE1) $(OBJS_COMMON)
	$(CC) $(OBJS_EXAMPLE1) $(OBJS_COMMON) $(LDFLAGS) -o $@

.c.o:
	$(CC) $(CFLAGS) -c $<

depend:
	$(CC) -MM $(CFLAGS) $(SRCS) > $(DEPENDS)

clean:
	@rm -rf $(DEPENDS) $(OBJS) $(TARGETS) *~

-include $(DEPENDS)
